name: Test Report

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1.4.2
        with:
          artifact: /test-results_(.*)/
          name: "NUnit Tests for $1"
          path: "*.xml"
          reporter: nunit
